### ISSUE TITLE
Does your image support multiple accounts?

### ISSUE THREAD

**Issue by BobWs** [christophkoenig/getmail#1]
How do I retrieve mail from multiple accounts?
http://pyropus.ca/software/getmail/faq.html#faq-how-multi

Any change you could add it if it isn't supported?

**Comment by BobWs** [comment]
Closed due to no response!

**Comment by christophkoenig** [comment]
Hello,

sorry, the email got lost in my spam folder it seems. I'll look into it.

**Comment by christophkoenig** [comment]
I updated the image and it should work with multiple accounts now: https://github.com/christophkoenig/getmail#multiple-accounts

**Comment by BobWs** [comment]
Thanks for updating. I’ll give it a try.

**Comment by BobWs** [comment]
I have tested the multiple accounts and it is working for me! Thanks for updating your image. 

Just one more question, does your container support gmail oauth? 
https://www.bytereef.org/howto/oauth2/getmail.html

**Comment by christophkoenig** [comment]
Hi, I didn't ignore this question but I haven't been able to test gmail oauth. I believe it won't work but I have no way to test it to make sure.
